# Generated by Django 5.2.7 on 2026-08-12 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_slug', models.SlugField(max_length=180)),
                ('player_name', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_sorare_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('player_name',),
                'constraints': [models.UniqueConstraint(fields=('user', 'player_slug'), name='unique_user_favorite_player')],
            },
        ),
    ]
