# Generated by Django 5.2.7 on 2026-08-24 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_movement_payment_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionRefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('quick', 'Actualizar pujas'), ('full', 'Buscar nuevas subastas')], max_length=8)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'Actualizando'), ('succeeded', 'Completada'), ('failed', 'Fallida')], db_index=True, default='queued', max_length=12)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('auction_count', models.PositiveIntegerField(default=0)),
                ('new_cards_count', models.PositiveIntegerField(default=0)),
                ('progress_label', models.CharField(blank=True, max_length=180)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorare_auction_refresh_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
