from django.urls import path

from . import direct_offer_views, views

urlpatterns = [
    path("healthz/", views.healthz, name="healthz"),
    path("", views.index, name="index"),
    path("telegram/", views.telegram_alerts, name="telegram_alerts"),
    path("puja/", views.bid_scheduler, name="bid_scheduler"),
    path("ventas/", views.sales_workbench, name="sales_workbench"),
    path("oportunidades/", views.opportunities, name="opportunities"),
    path("oportunidades/actualizar/", views.enqueue_opportunity_refresh, name="enqueue_opportunity_refresh"),
    path("oportunidades/estado/", views.opportunity_refresh_status, name="opportunity_refresh_status"),
    path("compras-instantaneas/", views.instant_purchases, name="instant_purchases"),
    path("compras-instantaneas/actualizar/", views.enqueue_instant_purchase_refresh, name="enqueue_instant_purchase_refresh"),
    path("compras-instantaneas/estado/", views.instant_purchase_refresh_status, name="instant_purchase_refresh_status"),
    path("lanzar-oferta/", direct_offer_views.direct_offers, name="direct_offers"),
    path("lanzar-oferta/jugadores/", direct_offer_views.direct_offer_player_search, name="direct_offer_player_search"),
    path("lanzar-oferta/ventas/", direct_offer_views.direct_offer_listings, name="direct_offer_listings"),
    path("lanzar-oferta/enviar/", direct_offer_views.create_direct_offer, name="create_direct_offer"),
    path("ventas/download/", views.sales_download_excel, name="sales_download_excel"),
    path("ventas/actualizar/", views.enqueue_sales_refresh, name="enqueue_sales_refresh"),
    path("ventas/encolar/", views.enqueue_batch_sales, name="enqueue_batch_sales"),
    path("ventas/estado/", views.sales_jobs_status, name="sales_jobs_status"),
    path("ventas/historial/", views.sales_price_history, name="sales_price_history"),
    path("movimientos/", views.movements, name="movements"),
    path("movimientos/analisis/", views.movement_analytics, name="movement_analytics"),
    path("movimientos/actualizar/", views.enqueue_movements_sync, name="enqueue_movements_sync"),
    path("movimientos/estado/", views.movements_sync_status, name="movements_sync_status"),
    path("ofertas/", views.auctions_list, name="auctions_list"),
    path("ofertas/actualizar/", views.enqueue_auction_refresh, name="enqueue_auction_refresh"),
    path("ofertas/actualizar/estado/", views.auction_refresh_status, name="auction_refresh_status"),
    path("ofertas/historial/", views.auction_price_history, name="auction_price_history"),
    path("ofertas/comparaciones/", views.auction_bid_comparisons, name="auction_bid_comparisons"),
    path("ofertas/favorito/", views.toggle_favorite_player, name="toggle_favorite_player"),
    path("ofertas/pujas/encolar/", views.enqueue_batch_bids, name="enqueue_batch_bids"),
    path("ofertas/pujas/estado/", views.bid_jobs_status, name="bid_jobs_status"),
    path("ofertas/filtros/guardar/", views.save_auction_filter, name="save_auction_filter"),
    path("ofertas/filtros/eliminar/", views.delete_auction_filter, name="delete_auction_filter"),
    path("ofertas-recibidas/", views.offers_received, name="offers_received"),
    path("ofertas-recibidas/precios/", views.offers_market_prices, name="offers_market_prices"),
    path("token/", views.refresh_token, name="refresh_token"),
]
